routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::redirect('/','/home');
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/inventory', 'InventoryController@index')->name('inventory');
Route::get('/orders', 'OrdersController@index')->name('orders');
Route::get('/product/{product_id}', 'ProductController@index')->name('product.show');

app/Inventory.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Inventory extends Model
{
    protected $table = 'inventory';

    public function product() 
    {
        return $this->belongsTo('App\Product');
    }

    public function orders() 
    {
        return $this->hasMany('App\Orders');
    }

    public function getPriceDollarsAttribute()
    {
        return number_format($this->price_cents / 100, 2);
    }

    public function getCostDollarsAttribute()
    {
        return number_format($this->cost_cents / 100, 2);
    }
}

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    public function product() 
    {
        return $this->belongsTo('App\Product');
    }

    public function inventory() 
    {
        return $this->belongsTo('App\Inventory');
    }

    public function getTotalDollarsAttribute()
    {
        return number_format($this->total_cents / 100, 2);
    }

    public function getTrackingNumberLinkAttribute()
    {
        switch ($this->shipper_name)
        {
            case "USPS":
                $link = "https://tools.usps.com/go/TrackConfirmAction?tLabels=" . $this->tracking_number;
                break;
            case "UPS":
                $link = "https://www.ups.com/track?loc=en_US&tracknum=" . $this->tracking_number;
                break;
            case "DHL":
                $link = "https://www.dhl.com/en/express/tracking.html?brand=DHL&AWB=" . $this->tracking_number;
                break;
            case "FedEx":
                $link = "https://www.fedex.com/apps/fedextrack/?tracknumbers=" . $this->tracking_number;
                break;
            default:
                $link = null;
        }
        return $link;
    }
}

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Kyslik\ColumnSortable\Sortable;

class Product extends Model
{
    public function inventory() 
    {
        return $this->hasMany('App\Inventory');
    }

    public function orders() 
    {
        return $this->hasMany('App\Orders');
    }

    public function getShippingPriceDollarsAttribute()
    {
        return number_format($this->shipping_price / 100, 2);
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function products() 
    {
        return $this->hasMany('App\Product','admin_id');
    }

    public function orders() 
    {
        return $this->hasManyThrough('App\Order','App\Product','admin_id');
    }


    public function inventory() 
    {
        return $this->hasManyThrough('App\Inventory','App\Product','admin_id');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     * 
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index(Request $request)
    {
        $id = $request->user()->id;
        $products = $request->user()->products()->orderBy('product_name')->paginate(20);
        return view('home', ['products' => $products]);
    }
}

app/Http/Controllers/InventoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class InventoryController extends Controller
{
     /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     * 
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index(Request $request)
    {
        $inv = $request->user()->inventory();
        $total_on_hand = $inv->sum('quantity');
        $unique_items = $inv->count();

        $inventory = $inv->orderBy('product_name');

        $filter = null;
        $below = null;

        if ($request->input('filter')) {
            $filter = $request->input('filter');
            $inventory = $inventory->where('product_name','LIKE','%'.$filter.'%')->orWhere('SKU','LIKE','%'.$filter.'%');
        }

        if ($request->input('below')) {
            $below = $request->input('below');
            $inventory = $inventory->where('quantity', '<', $below);

        }
        $inventory = $inventory->paginate(20);
        
        return view('inventory', [
            'inventory' => $inventory,
            'total_on_hand' => $total_on_hand,
            'unique_items' => $unique_items,
            'filter' => $filter,
            'below' => $below
        ]);
    }
}

app/Http/Controllers/OrdersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class OrdersController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     * 
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index(Request $request)
    {
        $o = $request->user()->orders();
        $total_sales = $o->sum('total_cents');
        $total_orders = $o->count();
        $average_per_sale =  number_format(($total_sales / 100) / $total_orders, 2);
        $total_sales_dollars = number_format($total_sales / 100, 2);
        $orders = $o->paginate(20);
        $grouped = $request->user()->orders()->groupBy('order_status')->selectRaw('count(*) as total, order_status')->get();

        return view('orders', ['orders' => $orders, 'total_sales' => $total_sales_dollars, 'average_per_sale' => $average_per_sale,'grouped'=>$grouped]);
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Product as Product; 

class ProductController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     * 
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index(Request $request, $product_id)
    {
        $user_id = $request->user()->id;
      
        $product = Product::where([
            ['id','=',$product_id],   
            ['admin_id','=',$user_id]
        ])->first();
  
        return view('product', ['product' => $product]);
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Products</div>
                <div class="card-body">
                    {{ $products->links() }}
                    <table class="table table-bordered">
                        <thead class="table-dark">
                            <tr>
                                <th>Name</th>
                                <th>Style</th>
                                <th>Brand</th>
                                <th>SKUs</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($products as $product)
                                <tr>        
                                    <td><a href="{{ route('product.show', ['product_id' => $product->id]) }}">{{ $product->product_name }}</a></td>
                                    <td>{{ $product->style }}</td>
                                    <td>{{ $product->brand }}</td>
                                    <td>
                                        @foreach ($product->inventory as $inventory)
                                            <a class="btn btn-light" href="{{ route('inventory',['filter'=>$inventory->sku]) }}">{{ $inventory->sku }}</a>
                                        @endforeach
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                    {{ $products->links() }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/inventory.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Inventory</div>
                <div class="card-body">
        
                    <div class="row">
                        <div class="col-md-6">
                            <div class="card">
                                <div class="card-header">
                                  Total Unique Items
                                </div>
                                <div class="card-body">
                                    {{ $unique_items }} 
                                </div>
                              </div>
                        </div>
                        <div class="col-md-6">
                            <div class="card">
                                <div class="card-header">
                                  Total Items On Hand:
                                </div>
                                <div class="card-body">
                                    {{ $total_on_hand }}
                                </div>
                              </div>
                        </div>
                    </div>
                    <hr />
                    
                    <div class="d-flex flex-row-reverse">
                        <form class="form-inline">
                            <div class="form-group mb-3">
                                <input type="text" class="form-control  form-control-sm" name="filter" placeholder="Product or SKU" value="{{ $filter ? $filter : "" }}">
                            </div>
                            <div class="form-group mx-sm-1 mb-2">
                            <button type="submit" class="btn btn-primary btn-sm mb-2">Search</button>
                            </div>
                            
                            <div class="form-group mx-sm-1 mb-2">
                            <a href="{{ route('inventory', ['below' => 10]) }}" class="btn btn-warning btn-sm mb-2">Show Low Inventory</a>
                            </div>
                            @if($filter or $below)
                            <div class="form-group mx-sm-1 mb-2">
                            <a href="{{ route('inventory') }}" class="btn btn-light btn-sm mb-2">Clear</a>
                            </div>
                            @endif

                        </form>
                    </div>

                    @if($filter)
                        {{ $inventory->appends(['filter'=>$filter])->links() }}
                    @elseif($below)
                        {{ $inventory->appends(['below'=>$below])->links() }}
                    @else
                        {{ $inventory->links() }}
                    @endif

                    <table class="table table-bordered">
                        <thead class="table-dark">
                            <tr>
                                <th>Product Name</th>
                                <th>SKU</th>
                                <th>Brand</th>
                                <th>Quantity</th>
                                <th>Color</th>
                                <th>Size</th>
                                <th>Price</th>
                                <th>Cost</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($inventory as $inv)
                                <tr>        
                                    
                                    <td><a href="{{ route('product.show', ['product_id' => $inv->product->id]) }}">{{ $inv->product->product_name }}</a></td>
                                    <td>{{ $inv->sku }}</td>
                                    <td>{{ $inv->product->brand }}</td>
                                    <td class="@if($inv->quantity < 1) table-danger @elseif ($inv->quantity < 10) table-warning @endif">{{ $inv->quantity }}</td>
                                    <td>{{ $inv->color }}</td>
                                    <td>{{ $inv->size }}</td>
                                    <td>${{ $inv->price_dollars }}</td>
                                    <td>${{ $inv->cost_dollars }}</td>
                                
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                    
                    @if($filter)
                        {{ $inventory->appends(['filter'=>$filter])->links() }}
                    @elseif($below)
                        {{ $inventory->appends(['below'=>$below])->links() }}
                    @else
                        {{ $inventory->links() }}
                    @endif

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('home') }}">Products</a>
                                    <a class="dropdown-item" href="{{ route('inventory') }}">Inventory</a>
                                    <a class="dropdown-item" href="{{ route('orders') }}">Orders</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/orders.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Orders</div>
                <div class="card-body">
                    
                    <div class="card">
                        <div class="card-header">
                          Sales Information
                        </div>
                        <div class="card-body">
                            <div class="d-flex justify-content-around">
                                    @foreach ($grouped as $group)
                                        <div>{{ $group->order_status }} Orders  <span class="badge">{{ $group->total }}</span></div>
                                    @endforeach
                                    <div>Averge Sale <span class="badge">${{ $average_per_sale }}</span></div>
                                    <div>Total Sales <span class="badge">${{ $total_sales }}</span></div>
                            </div>   
                        </div>
                    </div>
                   
                    <hr />

                    {{ $orders->links() }}
                    <table class="table table-bordered table-small">
                        <thead class="table-dark">
                            <tr>
                                <th>Customer Name</th>
                                <th>Email</th>
                                <th>Product Name</th>
                                <th>Color</th>
                                <th>Size</th>
                                <th>Order Status</th>
                                <th>Order Total</th>
                                <th>Shipper</th>
                                <th>Tracking Number</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($orders as $order)
                                <tr>        
                                    <td>{{ $order->name }}</td>
                                    <td>{{ $order->email }}</td>
                                    <td><a href="{{ route('product.show', ['product_id' => $order->product->id]) }}">{{ $order->product->product_name }}</a></td>
                                    <td>{{ $order->inventory->color }}</td>
                                    <td>{{ $order->inventory->size }}</td>
                                    <td>{{ $order->order_status }}{{ $order->transaction_id !== "NULL" ? " (" . $order->transaction_id . ")" : "" }}</td>
                                    <td>${{ $order->total_dollars }}</td>
                                    <td>{{ $order->shipper_name }}</td>
                                    <td>
                                        @if ($order->tracking_number_link)
                                            <a href="{{ $order->tracking_number_link }}" target="_blank">{{ $order->tracking_number }}</a>
                                        @else
                                            {{ $order->tracking_number }}
                                        @endif
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                    {{ $orders->links() }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/product.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        
            @if ($product)
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header">Product Info</div>
                    <div class="card-body">
                            <form>
                                <div class="form-group">
                                    <label for="productName">Product Name</label>
                                    <input type="text" class="form-control" id="productName" value="{{ $product->product_name }}">
                                </div>
                                <div class="form-group">
                                    <label for="description">Description</label>
                                    <input type="text" class="form-control" id="description" value="{{ $product->description }}">
                                </div>
                                <div class="form-group">
                                    <label for="style">Style</label>
                                    <input type="text" class="form-control" id="style" value="{{ $product->style }}">
                                </div>
                                <div class="form-group">
                                    <label for="brand">brand</label>
                                    <input type="text" class="form-control" id="brand" value="{{ $product->brand }}">
                                </div>
                                <div class="form-group">
                                    <label for="url">url</label>
                                    <input type="text" class="form-control" id="url" value="{{ $product->url }}">
                                </div>
                                <div class="form-group">
                                    <label for="product_type">product_type</label>
                                    <input type="text" class="form-control" id="product_type" value="{{ $product->product_type }}">
                                </div>
                                <div class="form-group">
                                    <label for="shipping_price">shipping_price</label>
                                    <input type="text" class="form-control" id="shipping_price" value="{{ $product->shipping_price }}">
                                </div>
                                <div class="form-group">
                                    <label for="note">note</label>
                                    <input type="text" class="form-control" id="note" value="{{ $product->note }}">
                                </div>
                                <button type="submit" class="btn btn-primary" disabled>Save</button>
                            </form>

                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header">Inventory</div>
                    <div class="card-body">
                        <table class="table table-bordered table-small">
                            <thead class="table-dark">
                                <tr>
                                    <th>sku</th>
                                    <th>quantity</th>
                                    <th>color</th>
                                    <th>size</th>
                                    <th>price</th>
                                    <th>cost</th>
                                </tr>
                            </thead>
                            <tbody>
                            @foreach ($product->inventory as $inv) 
                                <tr>   
                                    <td>{{ $inv->sku }}</td>
                                    <td class="@if($inv->quantity < 1) table-danger @elseif ($inv->quantity < 10) table-warning @endif">{{ $inv->quantity }}</td>
                                    <td>{{ $inv->color }}</td>
                                    <td>{{ $inv->size }}</td>
                                    <td>${{ $inv->price_dollars }}</td>
                                    <td>${{ $inv->cost_dollars }}</td>
                            @endforeach
                            </tbody>
                            </table>
                    </div>
                </div>
            </div>
            @else
            <div class="col-md-12">
                <div class="alert alert-danger" role="alert">
                    Sorry, we can not find the specified product.
                </div> 
            </div>     
            @endif
    </div>
</div>
@endsection